version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    networks:
      - nginx-network # NGINX와 통신하기 위해 동일한 네트워크 연결

networks:
  nginx-network:
    external: true # 외부에서 생성된 nginx-network를 사용
